name: 'action-visual-snapshot'
description: 'Visual snapshot tester for GitHub Actions'
author: 'Sentry'
inputs:
  snapshot-path:
    required: true
    description: 'path where snapshots are saved'
  diff-path:
    required: true
    description: 'path to write snapshot diffs'

  githubToken:
    required: true
    description: 'github token'

  base-workflow-id:
    required: false
    description: 'id of the workflow that saves your base snapshots (the name of the yaml file including extension)'
  base-branch:
    required: false
    description: 'name of the branch to use as base comparison'
    default: 'master'
  base-artifact-name:
    required: false
    description: 'the artifact name'
    default: 'visual-snapshots'

  gcp-service-account-key:
    required: false
    description: 'Google Cloud service account key (base64)'
  gcs-bucket:
    require: false
    description: 'if this is set, upload to google cloud storage'
outputs:
  diff-path:
    description: 'path to write snapshot diffs'
runs:
  using: 'node12'
  main: 'dist/index.js'
