name: 'action-visual-snapshot'
description: 'Visual snapshot tester for GitHub Actions'
author: 'Sentry'
inputs:
  threshold:
    description: 'Matching threshold, ranges from 0 to 1. Smaller values make the comparison more sensitive. 0.1 by default.'
    default: "0.05"
    required: false
  antialiasing:
    description: 'Blending factor of unchanged pixels in the diff output. Ranges from 0 for pure white to 1 for original brightness. 0.1 by default.'
    default: "false"
    required: false
  diffMask:
    description: 'Draw the diff over a transparent background (a mask), rather than over the original image. Will not draw anti-aliased pixels (if detected).'
    required: false

  snapshot-path:
    required: false
    description: 'path where snapshots are saved'
  merge-base:
    required: false
    description: 'the merge base sha, will use from github context otherwise. If you use `pull_request_target` you will need to supply the merge base.'

  api-token:
    required: true
    description: 'Visual Snapshot API token, should be `VISUAL_SNAPSHOT_SECRET` from GitHub Secrets'
  api-endpoint:
    required: false
    description: 'Custom API endpoint'

  github-token:
    required: false
    description: 'github token'
    default: '${{ github.token }}'

  results-path:
    required: false
    description: 'path to write snapshot diffs'
    default: '/tmp/visual-snapshot-results'
  save-only:
    required: false
    default: "false"
    description: 'should action only be used to save snapshots'
  base-workflow-id:
    required: false
    description: 'id of the workflow that saves your base snapshots (the name of the yaml file including extension)'
  base-branch:
    required: false
    description: 'name of the branch to use as base comparison'
    default: 'master'
  artifact-name:
    required: false
    description: 'the artifact name'
    default: 'visual-snapshots'

  action-name:
    required: false
    description: 'The name to be displayed in GitHub Checks'
    default: 'Visual Snapshot'

  gcp-service-account-key:
    required: false
    description: 'Google Cloud service account key (base64)'
  gcs-bucket:
    required: false
    description: 'if this is set, upload to google cloud storage'
  parallelism: 
    required: false
    description: 'number of threads to use when diffing images'
outputs:
  results-path:
    description: 'path where results are saved'
  base-images-path:
    description: 'path where base images are saved'
  merge-base-images-path:
    description: 'path where merge base images are saved'
runs:
  using: 'node16'
  main: 'dist/index.js'
