name: 'action-visual-snapshot'
description: 'Visual snapshot tester for GitHub Actions'
author: 'Sentry'
inputs:
  snapshot-path:
    required: true
    description: 'path where snapshots are saved'
  githubToken:
    required: true
    description: 'github token'

  results-path:
    required: false
    description: 'path to write snapshot diffs'
    default: '/tmp/visual-snapshot-results'
  save-only:
    required: false
    default: false
    description: 'should action only be used to save snapshots'
  base-workflow-id:
    required: false
    description: 'id of the workflow that saves your base snapshots (the name of the yaml file including extension)'
  base-branch:
    required: false
    description: 'name of the branch to use as base comparison'
    default: 'master'
  artifact-name:
    required: false
    description: 'the artifact name'
    default: 'visual-snapshots'

  gcp-service-account-key:
    required: false
    description: 'Google Cloud service account key (base64)'
  gcs-bucket:
    require: false
    description: 'if this is set, upload to google cloud storage'
outputs:
  results-path:
    description: 'path where results are saved'
  base-images-path:
    description: 'path where base images are saved'
  merge-base-images-path:
    description: 'path where merge base images are saved'
runs:
  using: 'node12'
  main: 'dist/index.js'
